### ISSUE TITLE
Section on Media Queries

### ISSUE THREAD

**Issue by smithtimmytim** [acl-services/code-styleguide#3]
A section on media queries should say how to write them and in what order they should be in the rules. Here is my proposal:

```scss
.class-name {
  background-color: #fff;
  margin-bottom: 1.5rem; 
  // Media Queries should always go last.
  @media #{$small-up} {
    background-color: #000;
  }
}
```

I believe we should avoid writing custom media queries because they can easily get out of hand. But if necessary, they should always build up; theoretically therefore, building mobile first.

```css
// Example from Foundation
@media only screen and (min-width: 40.063em) { }
```
